### PR TITLE
Model the Interface Class

### PR DESCRIPTION
**Pull request by neumantm**

### CODE REVIEW

**Comment by neumantm** [comment]
Model_CCIMS-Metamodel_Class_Diagram

**Review by spethso — APPROVED** [review]
Looks good. The diagram does not show directly that if a CrossComponentIssue concerns an interface, it also concerns the component which produces the interface. However, I think this might not be possible in UML class diagrams.

**Comment by neumantm** [comment]
> The diagram does not show directly that if a CrossComponentIssue concerns an interface, it also concerns the component which produces the interface

I added this constraint using the Object Constraint Language

**Comment by spethso** [comment]
This is a nice solution :-)

**Pull request merged**
