### PR TITLE
Add compositions to reach every class

### PR DESCRIPTION
**Pull request by neumantm**
Every object in our dataset should (transitivly)
be owned by the one CroCoIssueManagementSystem,
otherwise they would not be in our dataset.

This is also neccesarry for parsley to allow
creation of new objects of these classes.

### CODE REVIEW

**Comment by neumantm** [comment]
Model_CCIMS-Metamodel_Class_Diagram

**Review by spethso — APPROVED** [review]
That is a good point. The diagram looks fine.

**Comment by spethso** [comment]
Ahh, I forgot a point. Can you add component's interfaces in the diagram? A CrossComponentIssue can also affect a component's interface and, therefore, should be drawn in the graph at the interface's node.

**Comment by neumantm** [comment]
> Ahh, I forgot a point. Can you add component's interfaces in the diagram? A CrossComponentIssue can also affect a component's interface and, therefore, should be drawn in the graph at the interface's node.

Yes. Will do that in a seperate PR.

**Pull request merged**
