### PR TITLE
Initial model

### PR DESCRIPTION
**Pull request by neumantm**
Add the initial ecore model based on the paper "A Concept for Integrating Issue Managements of Independently Developed Components" from Speth et al

Currently missing:
  * Names of the associations
  * Outgoing multiplicity of one way associations

Currently not displayed in the representation:
  * "unique" label for association ends

### CODE REVIEW

**Comment by spethso** [comment]
Looks pretty good so far.
> Currently missing:
> 
> * Names of the associations
> * Outgoing multiplicity of one way associations
>   Currently not displayed in the representation:
> * "unique" label for association ends

Maybe you can ask @snowball77 how to get the missing parts into the (graphical) model.

**Comment by spethso** [comment]
Additionally, I just noticed that we need another class for the interface of a component. This should be connected to the component so that a component provides 0 to * interfaces. Furthermore, a CrossComponentIssue can then affect such an interface in addition to the corresponding component.

What do you think about it?

**Comment by neumantm** [comment]
> Additionally, I just noticed that we need another class for the interface of a component. This should be connected to the component so that a component provides 0 to * interfaces. Furthermore, a CrossComponentIssue can then affect such an interface in addition to the corresponding component.
> 
> What do you think about it?

Sounds good. But I think this should be in a separate PR. That way this PR is the initial version as depicted in your paper.

**Comment by neumantm** [comment]
Abandoned in favor of #2

**Pull request closed without merging**
